---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:216989142685:task-definition/harish-task:1"
        LoadBalancerInfo:
          ContainerName: "hacontainer"
          ContainerPort: 8080
